### DISCUSSION TITLE
Fooocus wont run.  RuntimeError Found no NVIDIA driver on your system.

### DISCUSSION THREAD

**Discussion by ActionBuns** [lllyasviel/Fooocus#2593] [Q&A] [answered]
Hi, I had Fooocus running fine on Colab, then I ran the downloadable version and it wouldn't run, asked me to update the drivers.

I used Geoforce extreme and updated to the latest driver, now when I run Colab I get the error

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver

I downloaded the Driver Nvidia Driver 531 laptop from the website and get the same error in Colab

when I run the downloadable version Fooocus now comes on "when it wouldn't before I updated the drivers" and starts creating an 

image, till it gets to the very end, then the image 

disapears and I'm left with

RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

another error i got on the downloadable version when creating an image was 

RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

I would like to get Fooocus working on Colab again because the images are slow to process on my laptop.

Any help would be greatly appreciated.

Thanks..

**Comment by poor7** [comment]
There is no need to update your driver using Colab. You probably ran out of free minutes on their T4 GPU for today.

**Reply by ActionBuns** [reply]
Ok I'm pretty new to this Thank you

**Reply by KEN-watts** [reply]
did it work? i am having the same error after downloading . Requirement already satisfied: pygit2==1.12.2 in /usr/local/lib/python3.10/dist-packages (1.12.2)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.21)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.0
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/content/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/Fooocus/launch.py", line 136, in <module>
    from webui import *
  File "/content/Fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/content/Fooocus/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/content/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/content/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/content/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/content/Fooocus/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/content/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Reply by mashb1t** [reply, marked as answer]
Make sure you're actually using a GPU instance like T4 or V100, not CPU/TPU only.

**Comment by KEN-watts** [comment]
I'm using T4 GPU

The problem started after trying to install fooocus offline. But my pc
doesn't have the specs. I deleted the files.


Now colab doesn't work anymore

Please help me get it back up

**Reply by mashb1t** [reply]
Colab and your local installation do not have any connection, except when you mount your loc files to Google Drive and mount it again on Colab.
I'd suggest to terminate the Colab instance and start fresh with a new one, just confirmed, Colab is working for me.

**Comment by KEN-watts** [comment]
Cannot connect to GPU backend
You cannot currently connect to a GPU due to usage limits in Colab.

Im getting that

**Comment by KEN-watts** [comment]
Actually thanks for hearing me out.

Does colab have time limit? Or GPU limit?
Because it's like it's trying to access Nvidia resources on my pc and i
don't have

**Reply by mashb1t** [reply]
It has, in both Free and Pro version. You can find more informaton about this directly in Colab.

**Reply by protonic** [reply]
must be.. to avoid exploitation

**Comment by KEN-watts** [comment]
i just switched the email and it magically worked . so happy right now omg

**Comment by adrianlemusic** [comment]
How long should I wait to use Fooocus via Colab again?

**Reply by mashb1t** [reply]
Please check the console output, there might be issues if it doesn't boot. It takes ~4min on the first boot for me.

**Comment by kiranborker** [comment]
RuntimeError: Found no NVIDIA driver on your system. same error. 

i changed the email and it worked and now after my internet was off for a while and back it doesn't work again. 

what can be the issue?
