### DISCUSSION TITLE
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.

### DISCUSSION THREAD

**Discussion by YPG-8-P1Guan** [lllyasviel/Fooocus#3917] [Q&A] [answered]
Does anyone know which version of pytorch can use cuda with 50 series cuda?

**Comment by Rogala** [comment, marked as answer]
[I think it's the same as for ComfyUI](https://github.com/comfyanonymous/ComfyUI/discussions/6643)

**Comment by alibakhtiari2** [comment]
Hi, I have fixed the issue. 
visit my repository . full instruction is there : https://github.com/alibakhtiari2/fooocusrtx508090
