### DISCUSSION TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### DISCUSSION THREAD

**Discussion by Bikunovvladboggart** [lllyasviel/Fooocus#4042] [Q&A] [answered]
Hello!
I`m just download the Foococus and then I start them I get error(win 10):
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

This error starts after upgrade to 5060ti

I try to reinstall python but it  did not work for me

Help pls!

**Comment by Rogala** [comment, marked as answer]
[Here](https://github.com/lllyasviel/Fooocus/discussions/4035#discussioncomment-13648479)

**Reply by Bikunovvladboggart** [reply]
Thx, I did a number of additional manipulations with reinstallation of various modules, plus your recommendation. Now it works. But the problems are clearly with the compatibility of the RTC 5060ti
