### DISCUSSION TITLE
CUDA error: no kernel image is available for execution on the device Question

### DISCUSSION THREAD

**Discussion by Imwalrus38** [lllyasviel/Fooocus#4056] [Q&A] [answered]
When I attempt to generate an image i get the error below.
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I have
RTX 5060 T 16gb ram GPU
64 GB Ram
AMD Ryzen 7.8700G w Radeon 780M Graphics processor
Cuda 12.8 installed
Programs and feature shows I have python 2.4 installed. Fooocus is using the embedded Python 3.13.5 verson.

What do I need to do to correct this error?

**Comment by mashb1t** [comment, marked as answer]
see https://github.com/lllyasviel/Fooocus/issues/4053#issuecomment-3070976060

**Reply by Imwalrus38** [reply]
I followed these instructions: and received an error.
    Make sure you have Cuda installed, version 12.8 https://developer.nvidia.com/cuda-12-8-0-download-archive
    now enter the python_embedded folder in foooocus, open a CMD terminal here
    type python.exe -m pip install --force-reinstall torch==2.7.0+cu128 --extra-index-url https://download.pytorch.org/whl/cu128

Error
Could not import runpy module
Traceback (most recent call last):
  File "<frozen runpy>", line 14, in <module>
ImportError: bad magic number in 'importlib': b'o\r\r\n'

i also these these instructions I do not have a folder named "Stability Matrix"

For my question above, asken google Gemini to create simply instruction based on this thread and it gave me this.
Have to try it when i got enough time. Looks valid?
Simple Instructions (for Windows):
Download the necessary files: Go to this website: https://huggingface.co/w-e-w/torch-2.6.0-cu128.nv. From there, you need to download two files ("torch" and "torchvision") that match your computer's Python version.
Find the Fooocus "virtual environment": Locate the folder on your computer where Fooocus keeps its own "tools." It's usually found here: C:\Users*your username*\AppData\Roaming\StabilityMatrix\Packages\Fooocus\venv\scripts.

**Reply by mashb1t** [reply]
do you mean these instructions after activating your venv?

`pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`

**Reply by Imwalrus38** [reply]
I'm sorry. I can't find Fooocus "Virtual Environment.. I don't see any folder names tools related to focus.

**Reply by Imwalrus38** [reply]
Can you give more details about activating the virtual environment. I'm not sure what that means.

**Reply by Rogala** [reply]
[ComfyUI, Fooocus, FramePack Performance Boosters for NVIDIA RTX 5000 Series (Windows)](https://github.com/Rogala/AI_Attention)

**Reply by Imwalrus38** [reply]
Thank you! that worked great.

**Reply by zToXiCll** [reply]
I have a 5070 and I've tried everything and it still doesn't work. I've even followed the tutorials in other threads but nothing, it still doesn't work. Can anyone help me?

Discord: vntoniiio.

**Reply by Rogala** [reply]
I would help, but I have trouble with the language of angels (English), so I can only read and try.

**Reply by zToXiCll** [reply]
add me on ds
