### ISSUE TITLE
Error when generating an image

### ISSUE THREAD

**Issue by BVasilevski** [lllyasviel/Fooocus#1064]
Hi. I just installed the model and when i try to generate any image it just throws an error on the web app. The console doesn't show anything, the error is just on the web app. 

Here is the console log as a file because it was too long:
[log.txt](https://github.com/lllyasviel/Fooocus/files/13505660/log.txt)

**Comment by mirek190** [comment]
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled



Do you have CUDA installed?

**Comment by BVasilevski** [comment]
I fixed it, i installed it incorrectly :)

**Comment by AdamBusfy** [comment]
How did you fixed it pls?

**Comment by trojanhorse1184** [comment]
How did you fix it ? I'm having the same problem

**Comment by lllyasviel** [comment]
hello if you see "Torch not compiled with CUDA enabled" then you are not following installation guides, see also
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by trojanhorse1184** [comment]
It just says error when I click on generate
