### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ihsanfd** [lllyasviel/Fooocus#1118]
"C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Loaded preset: C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\presets\realistic.json
Failed to load config key: {"path_checkpoints": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\checkpoints"} is invalid or does not exist; will use {"path_checkpoints": "../models/checkpoints/"} instead.
Failed to load config key: {"path_loras": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\loras"} is invalid or does not exist; will use {"path_loras": "../models/loras/"} instead.
Failed to load config key: {"path_embeddings": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\embeddings"} is invalid or does not exist; will use {"path_embeddings": "../models/embeddings/"} instead.
Failed to load config key: {"path_vae_approx": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\vae_approx"} is invalid or does not exist; will use {"path_vae_approx": "../models/vae_approx/"} instead.
Failed to load config key: {"path_upscale_models": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\upscale_models"} is invalid or does not exist; will use {"path_upscale_models": "../models/upscale_models/"} instead.
Failed to load config key: {"path_inpaint": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\inpaint"} is invalid or does not exist; will use {"path_inpaint": "../models/inpaint/"} instead.
Failed to load config key: {"path_controlnet": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\controlnet"} is invalid or does not exist; will use {"path_controlnet": "../models/controlnet/"} instead.
Failed to load config key: {"path_clip_vision": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\clip_vision"} is invalid or does not exist; will use {"path_clip_vision": "../models/clip_vision/"} instead.
Failed to load config key: {"path_fooocus_expansion": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\models\\prompt_expansion\\fooocus_expansion"} is invalid or does not exist; will use {"path_fooocus_expansion": "../models/prompt_expansion/fooocus_expansion"} instead.
Failed to load config key: {"path_outputs": "C:\\Users\\username\\OneDrive\\Masa\u00fcst\u00fc\\Programming\\Yeni klas\u00f6r\\Fooocus\\outputs"} is invalid or does not exist; will use {"path_outputs": "../outputs/"} instead.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\modules\patch.py", line 6, in <module>
    import fcbh.model_base
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
    _lazy_init()
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 674, in current_device
    _lazy_init()
  File "C:\Users\username\OneDrive\Masaüstü\Programming\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled"
When i tried to use realism.bat I can't generate anything.
Also when i tried run.bat and then pyraCanny or CPDS i get this error: "runtimeError: Could not allocate tensor with 266135020 bytes. There is not enough GPU video memory available!"
GPU: AMD 6900xt

**Comment by ljnath** [comment]
Same problem here with with RX5500M 4GB + Ryzen 5 5600H + 24GB.

**Comment by gsarapura** [comment]
Same problem in Windows 10 - Radeon RX 580

**Comment by onurkose** [comment]
@ihsanfd 

add --directml to your .bat files:
`.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml --preset realistic`

for the GPU memory problem, try adding 0 or 1 to --directml:
--directml 0 or --directml 1

**Comment by wasubire** [comment]
> @ihsanfd
> 
> add --directml to your .bat files: `.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml --preset realistic`
> 
> for the GPU memory problem, try adding 0 or 1 to --directml: --directml 0 or --directml 1

Thank you, this fixed the error. To use the GPU I used the option --directml 0

**Comment by ljnath** [comment]
@ihsanfd , can you try adding the argument `--lowvram` ? I fixed my memory issue with this.

**Comment by jferrettiboke** [comment]
I'm running on macOS, and passing `--cpu` works for me. However, slow AF. `python entry_with_update.py --cpu`

**Comment by ianhein** [comment]
Same problem, running Windows 10 - Radeon 5600XT 6GB

**Comment by ihsanfd** [comment]
> @ihsanfd
> 
> add --directml to your .bat files: `.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml --preset realistic`
> 
> for the GPU memory problem, try adding 0 or 1 to --directml: --directml 0 or --directml 1

Thank you for the response. Unfortunately, your answer didn't resolve my Gpu memory issue.

**Comment by acvcleitao** [comment]
I've been having this issue for like a week now

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#torch-not-compiled-with-cuda-enabled
