### ISSUE TITLE
Image creation issue on intel Mac when Moving to GPU

### ISSUE THREAD

**Issue by JoDeer** [lllyasviel/Fooocus#1152]
I installed the Mac version of fooocus but when I try to create an image it cancels at "Moving to gpu". Here is the error I get in the console:
RuntimeError: MPS backend out of memory (MPS allocated: 6.38 GB, other allocations: 454.09 MB, max allowed: 6.80 GB). Tried to allocate 20.00 KB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Total time: 13.12 seconds

Here are my MacBooks specs:
2,6 GHz 6-Core Intel Core i7
Radeon Pro 560X 4 GB
Intel UHD Graphics 630 1536 MB
32 GB 2400 MHz DDR4
MacOS Sonoma 14.0

Is there any way to use Fooocus with this Mac?
If not are there any alternatives?

I think this is the full log for this attempt:
Enter LCM mode.
[Fooocus] Downloading LCM components ...
[Parameters] Adaptive CFG = 1.0
[Parameters] Sharpness = 0.0
[Parameters] ADM Scale = 1.0 : 1.0 : 0.0
[Parameters] CFG = 1.0
[Parameters] Seed = 7785053145805253392
[Parameters] Sampler = lcm - lcm
[Parameters] Steps = 8 - 8
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ('sdxl_lcm_lora.safetensors', 1.0)] for model [/Users/jonathan/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [/Users/jonathan/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/Users/jonathan/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Loaded LoRA [/Users/jonathan/Fooocus/models/loras/sdxl_lcm_lora.safetensors] for UNet [/Users/jonathan/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 1.0.
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] container ship on fire, burning, intricate, elegant, highly detailed, light, colorful, sharp focus, symmetry, fine detail, beautiful, cinematic, background, professional, enhanced, warm colors, dynamic, energetic, loving, caring, generous, futuristic, best, novel, romantic, stunning, perfect, balanced, color, epic, fantastic, gorgeous, breathtaking, dramatic
[Fooocus] Encoding positive #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1344, 768)
Preparation time: 5.61 seconds
Using lcm scheduler.
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.39970141649246216, sigma_max = 14.614640235900879
Requested to load SDXL
Loading 1 new model
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.ff.net.0.proj.weight MPS backend out of memory (MPS allocated: 6.35 GB, other allocations: 433.81 MB, max allowed: 6.80 GB). Tried to allocate 50.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.ff.net.0.proj.weight MPS backend out of memory (MPS allocated: 6.35 GB, other allocations: 431.78 MB, max allowed: 6.80 GB). Tried to allocate 50.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.ff.net.2.weight MPS backend out of memory (MPS allocated: 6.37 GB, other allocations: 435.40 MB, max allowed: 6.80 GB). Tried to allocate 25.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.ff.net.2.weight MPS backend out of memory (MPS allocated: 6.37 GB, other allocations: 435.28 MB, max allowed: 6.80 GB). Tried to allocate 25.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.attn2.to_q.weight MPS backend out of memory (MPS allocated: 6.36 GB, other allocations: 454.02 MB, max allowed: 6.80 GB). Tried to allocate 6.25 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.attn2.to_q.weight MPS backend out of memory (MPS allocated: 6.36 GB, other allocations: 453.47 MB, max allowed: 6.80 GB). Tried to allocate 6.25 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.attn2.to_v.weight MPS backend out of memory (MPS allocated: 6.38 GB, other allocations: 428.24 MB, max allowed: 6.80 GB). Tried to allocate 10.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.0.1.transformer_blocks.5.attn2.to_v.weight MPS backend out of memory (MPS allocated: 6.38 GB, other allocations: 427.53 MB, max allowed: 6.80 GB). Tried to allocate 10.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Traceback (most recent call last):
  File "/Users/jonathan/Fooocus/modules/async_worker.py", line 803, in worker
    handler(task)
  File "/Users/jonathan/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jonathan/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jonathan/Fooocus/modules/async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "/Users/jonathan/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jonathan/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jonathan/Fooocus/modules/default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "/Users/jonathan/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jonathan/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jonathan/Fooocus/modules/core.py", line 315, in ksampler
    samples = fcbh.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/Users/jonathan/Fooocus/backend/headless/fcbh/sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
  File "/Users/jonathan/Fooocus/backend/headless/fcbh/sample.py", line 86, in prepare_sampling
    fcbh.model_management.load_models_gpu([model] + models, model.memory_required(noise_shape) + inference_memory)
  File "/Users/jonathan/Fooocus/modules/patch.py", line 494, in patched_load_models_gpu
    y = fcbh.model_management.load_models_gpu_origin(*args, **kwargs)
  File "/Users/jonathan/Fooocus/backend/headless/fcbh/model_management.py", line 410, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "/Users/jonathan/Fooocus/backend/headless/fcbh/model_management.py", line 293, in model_load
    raise e
  File "/Users/jonathan/Fooocus/backend/headless/fcbh/model_management.py", line 289, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
  File "/Users/jonathan/Fooocus/backend/headless/fcbh/model_patcher.py", line 194, in patch_model
    out_weight = self.calculate_weight(self.patches[key], temp_weight, key).to(weight.dtype)
  File "/Users/jonathan/Fooocus/modules/patch.py", line 75, in calculate_weight_patched
    mat1 = fcbh.model_management.cast_to_device(v[0], weight.device, torch.float32)
  File "/Users/jonathan/Fooocus/backend/headless/fcbh/model_management.py", line 534, in cast_to_device
    return tensor.to(device).to(dtype)
RuntimeError: MPS backend out of memory (MPS allocated: 6.38 GB, other allocations: 454.09 MB, max allowed: 6.80 GB). Tried to allocate 20.00 KB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Total time: 13.12 seconds

**Comment by mashb1t** [comment]
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1139

**Comment by Edion-Liu** [comment]
现在解决了？我也是mac 电脑，inte 显卡

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/discussions/1156
