### ISSUE TITLE
RuntimeError: CUDA error: an illegal instruction was encountered

### ISSUE THREAD

**Issue by Eagle447** [lllyasviel/Fooocus#1937]
**Describe the problem**
So, I was messing around with some Overclocking to get the most out of my GPU, and i was using Fooocus (obviously) for the benchmark. It crashed at a point, as expected, so I restarted it and lowered the MHz a little. I was supposed to get it working again, cause it was literally working just a minute before the crash, but i get this rare message. So I decided to close the MSI afterburner (without saving anything), and restarted fooocus, but the error is still there. What can I do to "not make it a permanent error" so I can use my overclocked GPU with fooocus without any problem?

**Full Console Log**
```
C:\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 14229 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [C:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 1.13 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 3748405380929098523
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] forest elf, extremely beautiful, intricate, elegant, highly detailed, wonderful quality, vibrant color, thought, dramatic light, iconic, fine balanced composition, elaborate great classic cinematic aesthetic, professional, winning, pure, fantastic, full artistic, cool, epic, awesome, creative, amazing, fabulous, lovely, symmetry, illuminated, incredible, very inspirational, brilliant, cute, colorful
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] forest elf, deep focus, beautiful, highly detailed, clear color, cinematic, dramatic ambient, professional, quality, perfect,,, epic, singular, shining, bright, spiritual, sharp,, emotional, cute, delicate, confident, passionate, extremely, charming, depicted, intricate, innocent, expressive, artistic, pure, colorful, light, mystical, determined, attractive
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.20 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 4.40 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 7.28 seconds
  0%|                                                                                           | 0/30 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "C:\Fooocus\Fooocus\modules\async_worker.py", line 823, in worker
    handler(task)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\Fooocus\modules\async_worker.py", line 754, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\Fooocus\modules\core.py", line 313, in ksampler
    samples = ldm_patched.modules.sample.sample(model,
  File "C:\Fooocus\Fooocus\ldm_patched\modules\sample.py", line 101, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Fooocus\Fooocus\ldm_patched\modules\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\Fooocus\modules\sample_hijack.py", line 157, in sample_hacked
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback_wrap, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Fooocus\Fooocus\ldm_patched\modules\samplers.py", line 561, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\Fooocus\ldm_patched\k_diffusion\sampling.py", line 701, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Fooocus\Fooocus\ldm_patched\k_diffusion\sampling.py", line 613, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Fooocus\Fooocus\modules\patch.py", line 314, in patched_KSamplerX0Inpaint_forward
    out = self.inner_model(x, sigma,
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Fooocus\Fooocus\ldm_patched\modules\samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
  File "C:\Fooocus\Fooocus\ldm_patched\modules\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "C:\Fooocus\Fooocus\modules\patch.py", line 229, in patched_sampling_function
    positive_x0, negative_x0 = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "C:\Fooocus\Fooocus\ldm_patched\modules\samplers.py", line 226, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\Fooocus\Fooocus\ldm_patched\modules\model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Fooocus\Fooocus\modules\patch.py", line 431, in patched_unet_forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, output_shape, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "C:\Fooocus\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 50, in forward_timestep_embed
    x = layer(x, output_shape=output_shape)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Fooocus\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 95, in forward
    x = F.interpolate(x, size=shape, mode="nearest")
  File "C:\Fooocus\python_embeded\lib\site-packages\torch\nn\functional.py", line 3983, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Total time: 15.54 seconds
```

**Comment by mashb1t** [comment]
Please check out these related issues: https://github.com/lllyasviel/Fooocus/issues/530, https://github.com/lllyasviel/Fooocus/issues/1096

You can further debug this issue by using `set CUDA_LAUNCH_BLOCKING=1` before executing Fooocus by modifying the run-bat file. Please provide additional debug results so this issue can be analysed further.

**Comment by Eagle447** [comment]
Hey @mashb1t, thanks for the reply. I added the `set CUDA_LAUNCH_BLOCKING=1` to my bat file, and it is working. But now the performance has decreased drastically. I was getting 1.98it/s on extreme speed before (With the overclock) and 1.8it/s without overclock. but now it has decreased to 1.60it/s. "Speed mode" is worse as well, now im getting s/it lol.

here's the new terminal log
```
C:\Fooocus>set CUDA_LAUNCH_BLOCKING=1

C:\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 14229 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [C:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.83 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 5571180704452988424
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] forest elf, deep focus, intricate, elegant, highly detailed, lush, dramatic light, magical, sharp, perfect, ambient composition, professional, best, smart, colorful, sunny, color, dynamic background, magic, shiny, unique, cute, beautiful, confident, epic, inspired, stunning, gorgeous, creative, awesome, illuminated, brilliant, amazing, artistic, winning
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] forest elf, epic new shiny background, creative, positive, vibrant, energetic, cinematic, complex, amazing composition, highly detailed, beautiful, elegant, sharp focus, professional color, wonderful, perfect, pretty, attractive, delicate, fine, awesome, colorful, intricate, brilliant, light, shining, rich, hopeful, stylish, lovely, majestic, coherent, bright, fantastic
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.18 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 6.65 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 6.97 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:36<00:00,  1.22s/it]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.20 seconds
Image generated with private log at: C:\Fooocus\Fooocus\outputs\2024-01-16\log.html
Generating and saving time: 45.58 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 2.04 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:31<00:00,  1.05s/it]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: C:\Fooocus\Fooocus\outputs\2024-01-16\log.html
Generating and saving time: 35.00 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.55 seconds
Total time: 90.54 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 7158680100116812113
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] forest elf, dramatic magic, background, sharp focus, highly detailed, cinematic, intricate, elegant, professional fine composition, colorful deep colors, beautiful dynamic, gorgeous futuristic, stunning, brilliant, symmetry, coherent, shiny, polished, pretty, illuminated, color, epic light, ambient, pristine, transparent, radiant, magical, full, open, glowing, bright, determined
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] forest elf, joyful, intricate, elegant, highly detailed, wonderful quality, light, sharp focus, pretty, attractive, modern, inspired, lush, background, professional, cute, expressive, beautiful, dramatic artistic, true colors, perfect, atmosphere, awesome, full, very inspirational, color, best, fine detail, clear, set, consistent, vivid, sleek, brilliant
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.18 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 4.21 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 2.48 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:31<00:00,  1.04s/it]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.16 seconds
Image generated with private log at: C:\Fooocus\Fooocus\outputs\2024-01-16\log.html
Generating and saving time: 35.23 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.96 seconds
  7%|█████▌                                                                             | 2/30 [00:03<00:45,  1.62s/it]
User stopped
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.59 seconds
Total time: 45.57 seconds
Enter LCM mode.
[Fooocus] Downloading LCM components ...
[Parameters] Adaptive CFG = 1.0
[Parameters] Sharpness = 0.0
[Parameters] ADM Scale = 1.0 : 1.0 : 0.0
[Parameters] CFG = 1.0
[Parameters] Seed = 7069590730571759314
[Parameters] Sampler = lcm - lcm
[Parameters] Steps = 8 - 8
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ('sdxl_lcm_lora.safetensors', 1.0)] for model [C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [C:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Loaded LoRA [C:\Fooocus\Fooocus\models\loras\sdxl_lcm_lora.safetensors] for UNet [C:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 1.0.
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus Model Management] Moving model(s) has taken 1.11 seconds
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] forest elf, strong, intricate, highly detailed background, cinematic, dynamic composition, dramatic light, elegant, focus, fair, beautiful, emotional, gorgeous, epic, amazing detail, saturated colors, surreal, very inspirational, friendly, thought, ambient, iconic, fine balanced color, great scientific, clear, crisp, artistic, hopeful, cute, aesthetic, pretty, marvelous
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] forest elf, sharp focus, highly detailed, cinematic, singular background, fine detail, dramatic light, open epic composition, surreal, symmetry, great classic, intricate, elegant, beautiful, amazing, artistic, ambient, dynamic, warm colors, professional, winning, new, best, awesome, creative, positive, thoughtful, vibrant, loving, healthy, unique, confident, attractive
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 6.89 seconds
Using lcm scheduler.
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.39970144629478455, sigma_max = 14.614640235900879
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 4.86 seconds
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.60it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: C:\Fooocus\Fooocus\outputs\2024-01-16\log.html
Generating and saving time: 11.40 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.39970144629478455, sigma_max = 14.614640235900879
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 2.60 seconds
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:04<00:00,  1.60it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: C:\Fooocus\Fooocus\outputs\2024-01-16\log.html
Generating and saving time: 9.11 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.57 seconds
Total time: 30.84 seconds
```

**Comment by mashb1t** [comment]
@Eagle447  were you able to further debug Fooocus / do you require further assistance?

**Comment by Eagle447** [comment]
@mashb1t Yes, Hello! Sorry I wasn't here for a week. I removed the `set CUDA_LAUNCH_BLOCKING=1` from the Run.bat file. But this time, fooocus doesn't keep crashing forever. It only crashes after a certain threshold, and after restarting, it just works fine. The problem was solved as if it never existed. So yes, This issue can be closed now.
