### ISSUE TITLE
Error when trying to generate image

### ISSUE THREAD

**Issue by Theo-Stefan** [lllyasviel/Fooocus#2071]
just downloaded Fooocus and when i try to generate an image it just shows me a red "error" on the screen
screenshot of the error: [https://prnt.sc/_aHHW2SnYX7h](url)

Here's my laptop's specs:
CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz   2.40 GHz
RAM: 16GB
GPU 0: INTEL(R) UHD Graphics 630
GPU 1: INVIDIA GeForce GTX 1050
2 Hard drives: 1) m2 SSD 256GB, 2) SSD 1TB with lots of free space (fooocus is installed in the 2nd disk)

FULL CONSOLE LOG:

D:\Programs\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.864
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Programs\Fooocus\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "D:\Programs\Fooocus\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "D:\Programs\Fooocus\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "D:\Programs\Fooocus\Fooocus\modules\patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\modules\model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\ldm\modules\attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 11010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
Traceback (most recent call last):
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "D:\Programs\Fooocus\Fooocus\webui.py", line 27, in generate_clicked
    import ldm_patched.modules.model_management as model_management
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "D:\Programs\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "D:\Programs\Fooocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 11010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by eddyizm** [comment]
Looks like the error is telling you what you need to do. Update your nvidia drive. 
```
RuntimeError: The NVIDIA driver on your system is too old (found version 11010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver.
```
Give that a go first before trying again.

**Comment by Theo-Stefan** [comment]
> Looks like the error is telling you what you need to do. Update your nvidia drive.
> 
> ```
> RuntimeError: The NVIDIA driver on your system is too old (found version 11010). Please update your GPU driver by   
> downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to:   
> https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver.
> ```
> 
> Give that a go first before trying again.

yes that was it, now it works thanks!!
Another issue though is that it takes me about 7 MINUTES to generate one picture, but I guess that's because of my GPU which isn't the best. I dont mind that it takes long time, but do you think it's dangerous for my computer? Will it get burnt like a toast?

**Comment by mashb1t** [comment]
This depends on the degree of GPU degradation on your side, but in general GPUs + their drivers do have mechanisms to thermal throttle to prevent overheating by regulating the clock frequency accordingly.
Closing this issue as solved.
