### ISSUE TITLE
CUDA asynchronous error

### ISSUE THREAD

**Issue by thegreenonion** [lllyasviel/Fooocus#212]
Hello guys!

I've got the following problem with Fooocus:
I have generated some pictures with Fooocus and everything worked fine, but when I want to use it now and generate a picture, Fooocus always fails at iteration 30/30, even though I haven't changed anything on my setup.
I also get a preview of the picture, but it can't be completed.

I already tried commenting line 84 in launch.py to disable cuda_malloc() and disabled the update in entry_and_update.py to keep the changes in launch.py but the error persists.

Hardware:
AMD Ryzen 5 2400G
Nvidia GeForce GTX 970
16 GB RAM
(I know this isn't so good but Fooocus already worked a few times on this hardware.)

Message:

App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
C:\Users\Emil\Pictures\Fooocus\python_embeded\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]C:\Users\Emil\Pictures\Fooocus\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
 67%|██████████████████████████████████████████████████████▋                           | 20/30 [03:00<01:25,  8.53s/it]Refiner swapped.
 93%|████████████████████████████████████████████████████████████████████████████▌     | 28/30 [04:34<00:18,  9.44s/it]C:\Users\Emil\Pictures\Fooocus\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py:585: UserWarning: Should have ta>=t0 but got ta=0.02916753850877285 and t0=0.029168.
  warnings.warn(f"Should have ta>=t0 but got ta={ta} and t0={self._start}.")
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [04:51<00:00,  9.73s/it]
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\modules\async_worker.py", line 104, in worker
    handler(task)
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\modules\async_worker.py", line 75, in handler
    imgs = pipeline.process(p_txt, n_txt, steps, switch, width, height, seed, callback=callback)
  File "C:\Users\Emil\Pictures\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\modules\default_pipeline.py", line 166, in process
    decoded_latent = core.decode_vae(vae=xl_base_patched.vae, latent_image=sampled_latent)
  File "C:\Users\Emil\Pictures\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\modules\core.py", line 67, in decode_vae
    return opVAEDecode.decode(samples=latent_image, vae=vae)[0]
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\nodes.py", line 241, in decode
    return (vae.decode(samples["samples"]), )
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 640, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples) + 1.0) / 2.0, min=0.0, max=1.0).cpu().float()
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\Emil\Pictures\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\modules\diffusionmodules\model.py", line 734, in forward
    h = nonlinearity(h)
  File "C:\Users\Emil\Pictures\Fooocus\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\modules\diffusionmodules\model.py", line 40, in nonlinearity
    return x*torch.sigmoid(x)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Can anyone help me?

Greetings,

thegreenonion

**Comment by Splathub** [comment]
@thegreenonion Ever find that solution?

**Comment by ShubhamBhanot29** [comment]
@thegreenonion @Splathub Hey did you guys find any solution?

**Comment by thegreenonion** [comment]
Well, I upgraded on a new graphics card that solved the problem for me

**Comment by erskyne** [comment]
anyone else find a solution?
@thegreenonion what did you upgrade from / to ?

**Comment by lllyasviel** [comment]
please follow official installation and install latest version.
make sure that you have enough system swap and latest nvidia driver.

**Comment by thegreenonion** [comment]
@erskyne I did upgrade from a NVIDIA GTX 970 to a NVIDIA RTX 3060ti and now everything runs smooth.

**Comment by Splathub** [comment]
@ShubhamBhanot29 sorry for the delay. Only saw the notification when it was closed :p 
I never updated my GPU, with certain settings it won't cause issues but still a few minutes of processing. Basically, don't go fancy and less cycles.
