### ISSUE TITLE
[Bug]: 5090 on Windows 10 CUDA error: no kernel image

### ISSUE THREAD

**Issue by BKR-dev** [lllyasviel/Fooocus#4032]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [x] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I downloaded the Windows release and installed it, when the webUI started i wrote a prompt and at generation the error came 

### Steps to reproduce the problem

1. Download Windows
2. Unzip
3. Run install.bat
4. Add prompt 
5. Click on generate

### What should have happened?

the generation should have happened 

### What browsers do you use to access Fooocus?

Brave

### Where are you running Fooocus?

Locally

### Console logs

```Shell
[Parameters] Adaptive CFG = 7
[Parameters] CLIP Skip = 2
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] Seed = 1130021938402545746
[Parameters] CFG = 4
[Fooocus] Loading control models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
Traceback (most recent call last):
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\modules\async_worker.py", line 1471, in worker
    handler(task)
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\modules\async_worker.py", line 1160, in handler
    tasks, use_expansion, loras, current_progress = process_prompt(async_task, async_task.prompt, async_task.negative_prompt,
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\modules\async_worker.py", line 738, in process_prompt
    expansion = pipeline.final_expansion(t['task_prompt'], t['task_seed'])
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\Fooocus\extras\expansion.py", line 120, in __call__
    features = self.model.generate(**tokenized_kwargs,
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\transformers\generation\utils.py", line 1664, in generate
    self._prepare_special_tokens(generation_config, kwargs_has_attention_mask, device=device)
  File "C:\Users\BKR\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\transformers\generation\utils.py", line 1513, in _prepare_special_tokens
    if eos_token_id is not None and torch.isin(elements=eos_token_id, test_elements=pad_token_id).any():
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Total time: 0.11 seconds
```

### Additional information

I had fooocus running in wsl2 on windows 11 but it doesnt seem to work native on windows 10 without wsl2

**Comment by BKR-dev** [comment]
i fixed it by updating the bundled cuda to 128 

` cd .\Downloads\Fooocus_win64_2-5-0\Fooocus_win64_2-5-0\python_embeded\
.\python.exe -m pip install --upgrade pip
.\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
`

and now it works perfectly.
