### ISSUE TITLE
[Feature Request]: # RTX 5060 (sm_120) Not Supported - CUDA Compatibility Issue

### ISSUE THREAD

**Issue by paladryenn11-alt** [lllyasviel/Fooocus#4123]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

## System Information
- **GPU**: NVIDIA GeForce RTX 5060
- **CUDA Capability**: sm_120 (Blackwell architecture)
- **Driver Version**: 581.57
- **OS**: Windows 11
- **Fooocus Version**: 2.5.0 (win64)

## Problem Description
Fooocus fails to start on RTX 5060 with the following error:

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

Full error message:
```
NVIDIA GeForce RTX 5060 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.
```

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

## What I Tried
1. ✅ Updated to latest NVIDIA driver (581.57)
2. ✅ Downloaded official Fooocus 2.5.0 from releases
3. ✅ Tried switching to CUDA 11 version (`previous_old_xformers_env.7z`)
4. ❌ Still getting the same compatibility error

## Root Cause
The RTX 50-series GPUs (including RTX 5060) use the new **Blackwell architecture** with **sm_120** compute capability, which is not yet supported by the current PyTorch version bundled with Fooocus.

## Request
Could you please:
1. Update PyTorch to a version that supports sm_120 architecture
2. Add RTX 50-series GPU support to Fooocus
3. Update the troubleshooting documentation with information about RTX 50-series compatibility

## Additional Context
The RTX 5060 was released in early 2025 and is becoming more common. This issue will likely affect many users upgrading to RTX 50-series cards.

## Workaround Status
Currently, there is **no working workaround** for RTX 50-series users. The application cannot run on these GPUs.

---

Thank you for your excellent work on Fooocus! I'm looking forward to using it once RTX 50-series support is added.

**Comment by zevnda** [comment]
Fixed for me by using pytorch nightly build `2.10.0`. Go to the directory where you unpacked Fooocus and run 
```
pip install --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
```

Follow [these steps](https://github.com/lllyasviel/Fooocus/issues/4123#issuecomment-3758780086) if you're confused about how to correctly install the nightly build for Fooocus

**Comment by bl4ckm0onk3y** [comment]
> Fixed for me by using pytorch nightly build `2.10.0`. Go to the directory where you unpacked Fooocus and run
> 
> ```
> pip install --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> ```

didn't work for me, tried this on my old and new Fooocus install, tried already everything, still no sm_120 for nvidia 5000 series.

**Comment by bgree825** [comment]
I am also having this issue on 5000 series and @zevnda 's fix didn't work for me either

**Comment by zevnda** [comment]
@bl4ckm0onk3y @bgree825 Can you clarify what "didn't work" means exactly? Did you get any errors when running the `pip install` command I suggested? Do you get the same error when running the `.bat` file or different errors, or something else entirely? I just tested the method I shared again, and it is still working for me.

To clarify, I am on Windows 11 Home (23H2), with an RTX5070 on the latest game-ready drivers.

1. Download Fooocus following the steps for Windows [here](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows)
2. Once you have decompressed the .7z file, open a CMD/PowerShell terminal in that directory, for example `C:\user\downloads\Fooocus` and run the `pip install` command that I posted

If that fails, make sure you update your NVIDIA drivers to the latest version, then in a clean virtualenv run
```
pip uninstall -y torch torchvision torchaudio && pip cache purge && pip install --upgrade --force-reinstall --pre --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
```

If that still isn't working, what is the output of both `nvidia-smi` and `python -c "import torch; print(torch.version, torch.version.cuda, torch.cuda.is_available())"`?

**Comment by bl4ckm0onk3y** [comment]
```

At line:1 char:47
+ pip uninstall -y torch torchvision torchaudio && pip cache purge && p ...
+                                               ~~
The token '&&' is not a valid statement separator in this version.
At line:1 char:66
+ ... install -y torch torchvision torchaudio && pip cache purge && pip ins ...
+                                                                ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

```

i'm getting this error while copy and paste your command,  Where is virtual env for focus located ? 


I have pyton 3.10.11 (custom path) and cuda 128 for stable diffusion webui forge and it works without problems.

- specs - RTX5070Ti cuda 128 and 131 packages installed, drivers are 591.74, on Microsoft Windows 11 [Version 10.0.26100.7623]

**Comment by zevnda** [comment]
@bl4ckm0onk3y Fooocus comes bundled with its own Python in `Fooocus\python_embedded`.

You don't need to touch your own install. I think this is where the miscommunication is. You should be running the `pip install` command with Python that is bundled with Fooocus, not your own install.

Here are the full steps. I will try to explain it in the easiest-to-follow way I can. If you can't get it to work from this, then I am not sure what else I can do to explain.

**DELETE ANY PREVIOUS FOOOCUS DIRECTORIES AND START FROM SCRATCH**
1. Download Foocus from here https://github.com/lllyasviel/Fooocus/releases/download/v2.5.0/Fooocus_win64_2-5-0.7z
2. Extract the `.7z` file somewhere you can easily find it, such as your desktop. You should now have a folder on your desktop called `Fooocus_win64_2-5-0`, the full path should be something like `C:\Users\your_username\Desktop\Fooocus_win64_2-5-0`
3. Open a new CMD terminal by pressing `WinKey+R` and typing `cmd` into the run dialog
4. In the CMD terminal, do `cd C:\Users\your_username\Desktop\Fooocus_win64_2-5-0` to navigate to the Fooocus folder
5. Paste the following command and hit enter
```
python_embeded\python.exe -m pip install --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
```
6. Let the download/install do its thing. Once it is finished, run the `run.bat` file

Let me know how you go.

**Comment by bl4ckm0onk3y** [comment]
> [@bl4ckm0onk3y](https://github.com/bl4ckm0onk3y) Fooocus comes bundled with its own Python in `Fooocus\python_embedded`.
> 
> You don't need to touch your own install. I think this is where the miscommunication is. You should be running the `pip install` command with Python that is bundled with Fooocus, not your own install.
> 
> Here are the full steps. I will try to explain it in the easiest-to-follow way I can. If you can't get it to work from this, then I am not sure what else I can do to explain.
> 
> **DELETE ANY PREVIOUS FOOOCUS DIRECTORIES AND START FROM SCRATCH**
> 
>     1. Download Foocus from here https://github.com/lllyasviel/Fooocus/releases/download/v2.5.0/Fooocus_win64_2-5-0.7z
> 
>     2. Extract the `.7z` file somewhere you can easily find it, such as your desktop. You should now have a folder on your desktop called `Fooocus_win64_2-5-0`, the full path should be something like `C:\Users\your_username\Desktop\Fooocus_win64_2-5-0`
> 
>     3. Open a new CMD terminal by pressing `WinKey+R` and typing `cmd` into the run dialog
> 
>     4. In the CMD terminal, do `cd C:\Users\your_username\Desktop\Fooocus_win64_2-5-0` to navigate to the Fooocus folder
> 
>     5. Paste the following command and hit enter
> 
> 
> ```
> python_embeded\python.exe -m pip install --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> ```
> 
>     6. Let the download/install do its thing. Once it is finished, run the `run.bat` file
> 
> 
> Let me know how you go.

This WORKED, but the main question is that i did this already once and it spit out the red wall of text.
One thing was different this time, i've deleted manually old python 3.12 from AppData. 
Probably something was borked in the old directory (by directory i mean Fooocus OLD)  since it has the python_embeded ¯\_(ツ)_/¯ 

Thank you for your help. ͡ಥ ͜ʖ ͡ಥ

**Comment by zevnda** [comment]
It's possible that `pip install ...` was using your system install (the one in AppData), even when running it from the `python_embedded` directory. Adding the `-m` flag along with the full path to the embedded Python ensures that we're using pip from the Fooocus installation instead.

But I'm glad you finally got it working, happy to help.

**Comment by etapic** [comment]
can confirm provided commands fixed issue, nvidia 5070ti , latest drivers, win11

**Comment by FabioLe23** [comment]
https://andreaskuhr.com/en/fooocus-forgewebui-automatic1111-nvidia-rtx-50xx-graphics-card.html
