### ISSUE TITLE
CUDA ERRORS/BLACK IMAGES GENERATED also  NVLDDMKM error on event viewer.

### ISSUE THREAD

**Issue by JustaLampPost** [lllyasviel/Fooocus#530]
Hello Guys!
 I need some help with this strange error maybe the Github community could help me with this. So first of all my PC Specs:
**I5 9600K 
RTX 2070 8GB
32GB RAM
ASUS Z390H MOBO
750W PSU**
So the thing is every time ill try to run Foocus its either generate full black image or crash with some cuda error i got at least 3 different  but basically all the same meaning i guess. All of them related to some illegal memory acces thing, or some kind of illegal call  _(Im at work right now but i could give more specific  info when i get home)_
After that i should restart the run bat but still really small chance to generate anything usable. I trying now for over 1 week but yet achive nothing all i could do is cca. 6 picture over 100 try.

 **(Note that # cuda alloc does not help at all. i tried to put my card to blacklist too still nothing.)**

The Nvlddmkm error is actually not new for me it was a pain in the arse for a long time when i tried to run a game but i doesnt know it was cuda related until i started to use Foocus. The error seemed to vanish at least i dont crash in games since it randomly fixed itself. But after i checked everything i thought its maybe caused by my rams because i could not turn XMP2 on Bios (without BSOD)  with the old 16GB sticks so i bought the new 32GB set of ram but it was unnecesary as it seems.
(*Its a comedy once in a while i want to stop gaming and do something usefull that maybe could be a sidehustle and this error start to haunt me again.*)

### Some of the error i got and found online from others (i found no usefull solution):

RuntimeError: CUDA error: API call is not supported in the installed CUDA driver
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
-------------------------------------------------------------------------------------------------------------------------------------------------
0%| | 0/30 [00:00<?, ?it/s]C:\Users\Feri\Pictures\Fooocus\python_embeded\lib\site-packages\torchsde_brownian\brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=14.614643096923828 and t1=14.614643.
warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
67%|██████████████████████████████████████████████████████▋ | 20/30 [03:00<01:25, 8.53s/it]Refiner swapped.
-------------------------------------------------------------------------------------------------------------------------------------------------
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
-------------------------------------------------------------------------------------------------------------------------------------------------
RuntimeError: CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
-------------------------------------------------------------------------------------------------------------------------------------------------
**On the event viewer:** 

_Nvlddmkm ID 0 13, 14_
-------------------------------------------------------------------------------------------------------------------------------------------------
\Device\Video3
21b3(31c0) 00000000 00000000
-------------------------------------------------------------------------------------------------------------------------------------------------
\Device\Video3
Graphics Exception: ESR 0x404490=0x80000040
-------------------------------------------------------------------------------------------------------------------------------------------------
\Device\Video3
Graphics SM Global Exception on (GPC 2, TPC 5, SM 1): Multiple Warp Errors
-------------------------------------------------------------------------------------------------------------------------------------------------
**Note maybe there is a some difference in these error messages i searched for them online but if more information needed please ask and i will send it later when i get home.** 

#
These are driver related errors or my GPU just dying already?

Thanks in advance!

**Comment by MoonRide303** [comment]
@JustaLampPost What driver are you using? For me [536.67](https://www.nvidia.com/download/driverResults.aspx/209265/en-us/) is working pretty fine, and 531 series should be pretty okay, too.

To check if your CPU & memory settings are okay you can use tools like [Prime95](https://www.mersenne.org/download/), and run stress tests for like 15-30 minutes. If you'll see any errors during that test you should fix those problems, first.

**Comment by JustaLampPost** [comment]
@MoonRide303 thanks for your answer. Im currently using the most recent driver i think it is the 536.67 i quess but i tried to go back for the 531 too but with the same result. Im gonna check my cpu and memory with this prime95. I tried to benchmark with other apps and had no issues yet. The only time my benchmark crashed was the EZbenchmark (somehow my card does crash while im using unreal engine games or apps.) But weird thing is furmark goes pretty well for more than 3 hours without any crash while  cpu burner running in the background. So i think my crashes fully cuda related. There is any possibility only the cuda processing unit (????) is faulty in a card or its only some kind of driver bug? (Sorry if this is a stupid question im a newbie in this) :D

**Comment by MoonRide303** [comment]
@JustaLampPost I never had this "illegal instruction" error from CUDA, so it's hard to guess. You can also try reinstalling CUDA - PyTorch 2.0.1 and 2.1 should work fine with [11.8](https://developer.nvidia.com/cuda-11-8-0-download-archive).

**Comment by JustaLampPost** [comment]
**UPDATE**
So first of all thanks for your help guys I really appreciate but sadly the problems still occurs so i was thinking that probably my 2070 simply dying. I went full yolo after this and bought a beast gamer laptop with an RTX4070  so i could work remotely with foocus and with the automatic1111....
But im getting the exact same errors....So before i take a bath with it (i dont have a toaster) there is anyone who has an idea what else i should try?

_the last error on my laptop:_ 

 File "E:\Fooocus_win64_2-0-50\Fooocus\modules\core.py", line 210, in preview_function
    x_sample = x_sample.cpu().numpy().clip(0, 255).astype(np.uint8)
RuntimeError: CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Total time: 9.34 seconds

**Comment by lllyasviel** [comment]
`CUDA kernel errors might be asynchronously reported at some other API call` was a old problem with `cuda_malloc.py`
The `cuda_malloc.py` was removed several weeks ago
Since you are on old `2-0-50`, you may want to try redownload fooocus and have fresh install and see if problem is fixed
