### ISSUE TITLE
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

### ISSUE THREAD

**Issue by heiheiheibj** [lllyasviel/Fooocus#73]
OS :WINSERVER2016
DEVICE:TESLA T4
CUDA Version: 12.2

  File "C:\Fooocus_win64_1-1-10\Fooocus\modules\core.py", line 190, in ksampler_with_refiner
    previewer = get_previewer(device, model.model.latent_format)
  File "C:\Fooocus_win64_1-1-10\Fooocus\modules\core.py", line 79, in get_previewer
    taesd = TAESD(None, taesd_decoder_path).to(device)
  File "C:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

THX..

**Comment by i-plusplus** [comment]
Can you check if sufficient free memory is available on GPU ?

**Comment by Kobaayyy** [comment]
same error, have u solved it?

**Comment by martinrosas84** [comment]
Hi guys! I solved that issue commenting the line that calls `cuda_malloc()` on launch.py file. @lllyasviel when you have time you can put the option --disable-cuda-malloc to skip that line. It happens on Centos, for example

**Comment by heiheiheibj** [comment]
@Kobaayyy commenting the line that calls cuda_malloc() on the launch.py . problem solved. 
@martinrosas84  thx .

**Comment by Kobaayyy** [comment]
> cuda_malloc()

@heiheiheibj @martinrosas84 thanks, solved it.

**Comment by emmanuelt445** [comment]
It's simple, remove --windows-standalone-build argument from the .bat file and put --disable-cuda-malloc
