### ISSUE TITLE
 API call is not supported in the installed CUDA driver

### ISSUE THREAD

**Issue by on1you** [lllyasviel/Fooocus#95]
return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: API call is not supported in the installed CUDA driver
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

torch2.0.1+cu117

**Comment by 0rthod0x** [comment]
What worked for me was installing the CUDA package version 12.

**Comment by martinrosas84** [comment]
Hi guys! I don't know if is the same error, but I solved a similar issue commenting the line that calls `cuda_malloc()` on launch.py file. Look at here: https://github.com/lllyasviel/Fooocus/issues/73

**Comment by on1you** [comment]
@martinrosas84 thanks, problem solved
